name = input("Enter your name : ")
print('Hi', name)
print("How old are you?", end=' ')
age = input()
print ("type of age", type(age))
print("How tall are you?", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()

print(f"So, you're {age} old, {height} tall and {weight} heavy.")
